### ISSUE TITLE
Contributor Request

### ISSUE THREAD

**Issue by cameronRomo** [orlovorlov/colorandom#4]
Hi, ya'll! My name is Cameron, Nickoli's mentor. If you're all up for it, could someone give access to me when they have a moment? This will make it easier to request me for PR reviews if you would like that. Also, it will make it easier to pull down a branch to help understand any issues/blockers from my own machine. If this sounds good, you can use my username to add me, which is: cameronRomo

![spy](https://media.giphy.com/media/120kDB2lOrYnV6/giphy.gif)

**Comment by orlov-n** [comment]
Hey Cameron!  Welcome aboard!  I tried assigning you, but I'm not sure if it worked or not.  Let me know.  Thanks.

**Comment by cameronRomo** [comment]
Actually, I don't think it did. If you go to settings/contributors, and add me there, that should do the trick 😁

**Comment by cameronRomo** [comment]
Thank you!! That worked!
